// Generates src/race/staffGhosts.json: one STAFF reference lap per race course
// (normal direction), driven offline by the game's own autopilot.
//
//   npx tsx scripts/make-staff-ghosts.ts [trackId...]
//
// For each course, every boat runs a deterministic headless time trial
// (4 laps on a loop, the single run on a sprint) with the autopilot — the
// same AIDriver the rivals use, on the same physics, no AI-only forces. The
// fastest recorded lap of all of them becomes the staff ghost. The fixed-step
// simulation makes the output reproducible run to run.
import { readFileSync, writeFileSync } from 'node:fs';
import { EventQueue } from '../src/core/events';
import { RaceSession, GHOST_HZ, type GhostData } from '../src/race/session';
import { defaultLivery } from '../src/boat/livery';
import { BOATS } from '../src/boat/specs';
import { TRACKS } from '../src/race/trackDefs';
import { packStaffSamples, resampleGhost, unpackStaffSamples, type StaffGhostFile } from '../src/race/staffGhosts';

const OUT = new URL('../src/race/staffGhosts.json', import.meta.url);
const STORE_HZ = 5;
const only = process.argv.slice(2);

const file: StaffGhostFile = JSON.parse(readFileSync(OUT, 'utf8'));
file.format = 'riptide-staff-ghosts/1';
file.note = 'AI reference laps: best autopilot lap per course (normal direction) over every boat, generated by scripts/make-staff-ghosts.ts. Samples: x,y,z,heading,pitch,roll quantised like ghost codes, Int16 LE deltas, base64.';
file.hz = STORE_HZ;

function bestLapFor(trackId: string, boatId: string): GhostData | null {
  const def = TRACKS.find((t) => t.id === trackId)!;
  const ev = new EventQueue();
  const s = new RaceSession({ mode: 'timetrial', trackId, weather: def.weather, laps: def.sprint ? 1 : 4, difficulty: 'normal', playerBoat: boatId as 'speedster', playerLivery: defaultLivery(), playerName: 'STAFF', opponents: 0, ghost: null }, ev);
  s.playerAutopilot = true;
  let t = 0;
  while (s.phase !== 'results' && t < 600) {
    s.step(1 / 60);
    t += 1 / 60;
    ev.clear();
  }
  return s.newGhost;
}

for (const def of TRACKS) {
  if (only.length && !only.includes(def.id)) continue;
  let best: GhostData | null = null;
  const tried: string[] = [];
  for (const b of BOATS) {
    const g = bestLapFor(def.id, b.id);
    tried.push(`${b.id} ${g ? g.time.toFixed(2) : '—'}`);
    if (g && (!best || g.time < best.time)) best = g;
  }
  if (!best) {
    console.log(`${def.id}: no lap recorded`);
    continue;
  }
  const stored = resampleGhost(best.samples, GHOST_HZ, STORE_HZ);
  const data = packStaffSamples(stored);
  // Round-trip check: positions must come back within a few centimetres.
  const back = unpackStaffSamples(data);
  let err = 0;
  for (let i = 0; i < stored.length; i += 6) err = Math.max(err, Math.hypot(back[i] - stored[i], back[i + 2] - stored[i + 2]));
  file.ghosts[def.id] = { boat: best.boatId, time: Math.round(best.time * 1000) / 1000, data };
  console.log(`${def.id.padEnd(10)} staff ${best.time.toFixed(2)} (${best.boatId})  ${(data.length / 1024).toFixed(1)} KB  maxErr ${(err * 100).toFixed(1)} cm   [${tried.join(', ')}]`);
}

writeFileSync(OUT, JSON.stringify(file) + '\n');
console.log(`wrote ${OUT.pathname} (${(JSON.stringify(file).length / 1024).toFixed(0)} KB)`);
