// Measures REVERSE / MIRROR / MIRROR+REVERSE medal times and writes src/race/variantMedals.ts.
//
//   npx tsx scripts/variant-medals.ts
//
// Method (same autopilot as harness/medal-probe.ts, which calibrated the normal
// medals): drive each course variant headless with the SPEEDSTER autopilot
// (5 laps on a loop, the single run on a sprint) and take the best lap. Each
// variant's medals are the normal course's medals scaled by the ratio of the
// variant's autopilot lap to the normal autopilot lap, so every variant keeps
// its course's calibration (bronze ≈ steady clean pace, gold ≈ 10% faster).
import { writeFileSync } from 'node:fs';
import { EventQueue } from '../src/core/events';
import { RaceSession } from '../src/race/session';
import { defaultLivery } from '../src/boat/livery';
import { TRACKS } from '../src/race/trackDefs';
import { courseKey, VARIANT_IDS, type CourseVariant } from '../src/race/variants';

function autopilotLap(trackId: string, variant: CourseVariant) {
  const def = TRACKS.find((t) => t.id === trackId)!;
  const ev = new EventQueue();
  const s = new RaceSession({ mode: 'timetrial', trackId, variant, weather: 'clear', laps: def.sprint ? 1 : 5, difficulty: 'normal', playerBoat: 'speedster', playerLivery: defaultLivery(), playerName: 'YOU', opponents: 0, ghost: null }, ev);
  s.playerAutopilot = true;
  let t = 0;
  while (s.phase !== 'results' && t < 600) {
    s.step(1 / 60);
    t += 1 / 60;
    ev.clear();
  }
  return s.player.bestLap;
}

const r1 = (x: number) => Math.round(x * 10) / 10;
const rows: string[] = [];
for (const def of TRACKS) {
  const base = autopilotLap(def.id, 'normal');
  const line: string[] = [`${def.id.padEnd(10)} normal ${base.toFixed(2)} medals ${def.medals.join('/')}`];
  for (const v of VARIANT_IDS) {
    if (v === 'normal') continue;
    const lap = autopilotLap(def.id, v);
    const k = lap / base;
    const m = def.medals.map((x) => r1(x * k)) as [number, number, number];
    rows.push(`  '${courseKey(def.id, v)}': [${m.join(', ')}], // autopilot ${lap.toFixed(2)} s (normal ${base.toFixed(2)})`);
    line.push(`${v} ${lap.toFixed(2)} → ${m.join('/')}`);
  }
  console.log(line.join(' | '));
}

const src = `/**
 * Time-trial medal targets for REVERSE / MIRROR course variants (gold, silver,
 * bronze, seconds), keyed by course key. GENERATED by scripts/variant-medals.ts:
 * each variant's autopilot best lap was measured headless and the course's
 * normal medals scaled by (variant lap / normal lap). Re-run after changing
 * the course generator or the physics.
 */
export const VARIANT_MEDALS: Record<string, [number, number, number]> = {
${rows.join('\n')}
};
`;
writeFileSync(new URL('../src/race/variantMedals.ts', import.meta.url), src);
console.log('wrote src/race/variantMedals.ts');
